# Config file to test the performance of a random AlexNet on a subset of ImageNet.

data_folder: /Users/mafaldafrere/Documents/Cours/IODAA/COMPUTER_VISION/DL4IA/docs/tutorials/learning_visual_representations/data_td3/subset_imagenet
labels_file: /Users/mafaldafrere/Documents/Cours/IODAA/COMPUTER_VISION/DL4IA/docs/tutorials/learning_visual_representations/data_td3/imagenet_labels.txt

subset_classes: [2, 3, 4, 6, 43, 203, 400, 600, 700, 800]
data_mean: [0.485, 0.456, 0.406]
data_std: [0.229, 0.224, 0.225]

epochs: 100
batch_size: 64
lr: 0.001
device: 'cuda'
val_split: 0.2
transforms:
  - center_crop
  - normalize
crop_size: 224
n_classes: 10
res_dir: /Users/mafaldafrere/Documents/Cours/IODAA/COMPUTER_VISION/DL4IA/docs/tutorials/learning_visual_representations/data_td3/results
